name: Release to WordPress.org

on:
    release:
        types: [ released ]

jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/wp-org-release.yml@master
        with:
            wp_org_slug: give-donation-modules-for-divi
            zip_name: give-divi
            text_domain: give-divi
        secrets:
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
            SLACK_ANNOUNCEMENT_WEBHOOK: ${{ secrets.SLACK_ANNOUNCEMENT_WEBHOOK }}
